# Basic
title: Dancel
subtitle: 个人学习与知识的沉淀。
welcome_message: blog分享学习经验，积累知识，记录生活点滴！
description: 现居深圳，作为运营狗，向往大前端的路
creator: <a href="meilto:326616437@qq.com">@ me</a>

url: "https://secret-k.github.io"

permalink: /:year/:month/:title/

# Format
<<<<<<< HEAD
highlighter: Baby blue
=======
highlighter: rgb(137, 207, 240)
>>>>>>> origin/master

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: grey

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 进入博客

# Navigation buttons in the front page.
nav:
    - {title: 作品, description: 我的项目, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: dancel
    github: secret-k
    twitter: dancel
    gplus: dancel
    mail: 326616437@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
